# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a7e30c1095e49ccef7561bf4156c09b5ca67a9b128487a1963d3e0c65bc103549f101c7145b874c5744389301dba37aa68f5c3429fdc9c3969d2263fb36852e

test:
  secret_key_base: 5794d3d93e785afec4cb57431449540d9acc50ca3794d7be4a30e81b5af6058ea5d88dab57e50d990ce482d4a1799ebbf2a0a66c75163f48b4b5d5bde0176808

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
